# 性激素相关知识

## 性激素检测项目及生理意义

严格意义上，只有雌激素、孕激素、雄激素属于性激素，这三种性激素均有多种类型及其衍生物和代谢产物，临床上通常测定的是雌二醇 ($E_2$)、孕酮 ($P$)、总睾酮 ($T$)。而促卵泡生长素 ($FSH$)、促黄体生成素 ($LH$) 和催乳素 ($PRL$) 与性激素关系密切，相互协调，故统称为性激素六项 ($FSH$、$LH$、$E_2$、$P$、$T$、$PRL$)。

### 促卵泡生长素 ($FSH$)

**来源**：FSH 是由垂体前叶促性腺激素细胞所分泌的促性腺激素之一。

**主要生殖生理作用**：

(1) 直接促进窦前卵泡及窦状卵泡中颗粒细胞的分裂增殖，使卵泡生长发育。
(2) 在前一周期的黄体晚期及本周期的早卵泡期，募集卵巢内窦卵泡；促使颗粒细胞合成分泌胰岛素样生长因子 ($IGF$) 及其受体、抑制素等物质，并与这些物质协同，调节优势卵泡的选择和非优势卵泡的闭锁退化。
(3) 诱导颗粒细胞内芳香化酶的产生，合成与分泌雌二醇；FSH 诱导细胞色素 P450 还原酶的表达，后者转运电荷给芳香化酶型 $17\beta$-羟甾脱氢酸，将雌酮还原成雌二醇。
(4) 晚卵泡期，与雌激素协同，诱导排卵前卵泡的颗粒细胞上形成 LH 受体，为卵泡排出及颗粒细胞黄素化做准备。

### 促黄体生成素 ($LH$)

**来源**：LH 是由垂体前叶促性腺激素细胞所分泌的第二种促性腺激素。

**主要生殖生理作用**：

(1) 在卵泡期刺激卵泡膜细胞合成雄激素，主要是雄烯二酮，为颗粒细胞芳香化（雌二醇的合成）提供底物，使较小卵泡的生长延缓，并抑制芳香化酶活性，从而把多卵泡发育减少到最低程度。
(2) 排卵前促使卵母细胞最终成熟及排卵。
(3) 在黄体期维持黄体功能，促进孕激素、雌二醇和抑制素 A 的合成与分泌。

### 雌二醇 ($E_2$)

**来源**：$E_2$ 主要由卵泡的颗粒细胞和排卵后的黄体细胞产生，妊娠后胎盘分泌。

**主要生殖生理作用**：

(1) 有效促进子宫内膜增殖及女性第二性征的发育。
(2) 早、中卵泡期，雌激素抑制性负反馈作用于下丘脑，改变促性腺激素释放激素 ($GnRH$) 脉冲的振幅和频率，并降低垂体对 $GnRH$ 的反应性，实现对垂体促性腺激素脉冲式分泌的抑制。
(3) 晚卵泡期，雌激素分泌达到阈值 ($\ge 200\sim300pg/ml$) 并维持 $48.7\pm9.3$ 小时以上，此时雌激素发挥促进性正反馈作用，刺激 LH 与 FSH 分泌升高至峰值。
(4) 黄体期和妊娠后，黄体细胞和胎盘分泌雌激素，为妊娠提供需求，如增加子宫血供、刺激子宫平滑肌拉长肥大、刺激催乳素分泌等。

### 孕酮 ($P$)

**来源**：P 主要由卵巢黄体分泌，妊娠后由胎盘分泌。

**主要生殖生理作用**：

(1) 有效促进增殖期子宫内膜向分泌期转化，其浓度与黄体的生长与退化密切相关。
(2) 排卵前稍升高的孕酮水平可增强雌激素对促性腺激素的促进性正反馈作用，黄体期高水平孕激素对促性腺激素脉冲式分泌产生抑制性负反馈作用。
(3) 黄体期和妊娠后，黄体细胞和胎盘分泌孕激素，有利于胚胎种植和维持妊娠。

### 睾酮 ($T$)

**来源**：T 主要由肾上腺和卵巢分泌。

**主要生殖生理作用**：

(1) 参与卵泡生长和卵子成熟的调节，T 增高将抑制下丘脑-垂体功能，或直接对抗雌激素而抑制卵泡发育成熟及排卵，导致其闭锁；其水平随月经周期而略有不同。
(2) 提高性欲。

### 催乳素 ($PRL$)

**来源**：PRL 主要由垂体前叶催乳素细胞分泌，孕期蜕膜产生 PRL，导致羊水中 PRL 浓度比母体血中的高 $10\sim100$ 倍。

**主要生殖生理作用**：

(1) 母体 PRL：促进乳腺发育与乳汁分泌。
(2) 蜕膜 PRL 的功能尚不清楚。

---

此外，性激素结合球蛋白 ($SHBG$)、硫酸脱氢表雄酮 ($DHEA-S$) 和雄烯二酮 ($ASD$) 也和性激素的水平息息相关，其具体生理作用如下。

### 性激素结合球蛋白 ($SHBG$)

**来源**：SHBG 主要是由肝细胞合成的一种能结合性激素的球蛋白，是血清中的一种糖蛋白。

**主要生理作用**：
SHBG 是一种运输性激素的载体，与类固醇高度特异性结合，包括睾酮、二氢睾酮以及雌二醇。这些激素与 SHBG 结合后会失去生物活性，因此 SHBG 水平在性激素作用过程中以及在各种生理病理情况下都有变化。

### 硫酸脱氢表雄酮 ($DHEA-S$)

**来源**：$DHEA-S$ 大部分在肾上腺或腺外组织经磺酸化后以硫酸盐式存在，其分泌由垂体促肾上腺皮质激素 ($ACTH$) 和其他垂体因素控制。

**主要生理作用**：

(1) 在男性青春期第二性征发育中起重要作用。
(2) 可被机体代谢转变为睾酮、雄烯二酮等活性更强的雄激素，或转变为雌激素。

### 雄烯二酮 ($ASD$)

**来源**：LH 刺激卵巢和睾丸释放 ASD，促肾上腺皮质激素刺激肾上腺释放 ASD。血液中 ASD 的含量常以“昼夜模式”变化，并且随女性的月经周期而略有不同。

**主要生理作用**：

(1) 可被机体转化为更有效的雄激素（如睾酮）或雌激素。
(2) 影响男性和女性发生性别分化以及男性第二性征（如声音低沉、长出胡须）发育。
(3) 可用作肾上腺功能、雄激素生成及睾丸功能的标志物。

## 性激素的生理变化

在规律的月经周期中，随着卵泡的募集生长以及优势卵泡的形成，性激素发生规律性的波动。了解卵泡生长及性激素的变化规律有助于在临床工作中更透彻地分析、理解病情变化，指导治疗。

正常的月经周期范围为 $21\sim35$ 天，本章节中描述的性激素水平的生理变化，来自最标准的 28 天月经周期的模式。

### 促卵泡生长素 (FSH)

(1) FSH 水平在 LH 峰值后 $12\sim13$ 天或经前 $2\sim4$ 天出现上升趋势，至下一周期的早卵泡期，升高的 FSH 开始募集卵泡，刺激处于有发育倾向的卵泡生长。如果卵泡易于生长，较低的 FSH 水平就可以满足募集卵泡的需求；如果动员卵泡生长困难，FSH 水平就会升高，以达到刺激卵泡生长的目的，所以通常认为 FSH 水平超过 $10\sim12IU/L$ 时，提示卵巢功能下降。FSH 是短暂的脉冲分泌的，同一天的不同时间测定，结果会有 $1\sim3IU/L$ 的差别。
(2) 在早卵泡期，小卵泡分泌的雌激素水平较低，随着被募集的几个卵泡的长大，分泌的雌激素水平逐渐升高；月经周期的第 $4\sim5$ 天之后，升高的雌激素（刺激抑制素 B 的升高）对 FSH 产生抑制性的负反馈作用，FSH 水平开始逐渐降低。尽管 FSH 降低，最敏感的一个卵泡仍会继续生长，其余的卵泡走向闭锁，起到二次优选卵泡的作用。
(3) 在晚卵泡期，优势卵泡渐趋成熟，处于排卵前期。排卵前促性腺激素波峰的出现是快速增高的雌二醇正反馈的结果。雌二醇可以直接作用于垂体，在雌激素水平快速增加的晚卵泡时期，垂体敏感性和释放促性腺激素的能力增加超过 20 倍；同时，FSH 诱导大卵泡（直径 $14mm$ 以上）内颗粒细胞上 LH 受体的表达，为接受 LH 的作用做好准备。约在月经周期第 13 天，血循环中 $E_2$ 浓度达到峰值，平均可达 $200\sim300pg/ml$。在月经周期的第 14 天，即排卵前一天出现 FSH 峰值（最高可达 $50\sim80IU/L$），同时也有 LH 峰值出现。
(4) 排卵后，FSH 血清浓度迅速下降，并一直保持下降趋势直至黄体中期。抑制素 A、雌二醇和孕酮（孕酮对 LH 抑制作用较强）同时抑制了 FSH 至最低点，从而在黄体早、中期阻断启动卵泡发育。
(5) 进入黄体晚期，随着黄体的萎缩，$E_2$ 及 P 水平的下降，对 FSH 的抑制性负反馈作用解除，表现出在下一次月经来潮前 $2\sim4$ 天 FSH 分泌逐渐升高，启动募集下一个月经周期的卵泡生长发育。因此认为卵泡的发育始于前一周期的黄体晚期，并持续至本周期的排卵前。

### 黄体生成素 (LH)

(1) LH 在早、中卵泡期一直维持低水平（明显低于 FSH 水平）。LH 是短暂的脉冲分泌的，同一天不同时间点的测定结果会有 $1\sim3IU/L$ 的差别，而且在卵巢功能衰退时，会随着 FSH 上升而升高。正常情况下，基础 LH 水平不高于 FSH 水平。
(2) 随着卵泡的生长，LH 呈极缓慢上升。在排卵前 3 天（优势卵泡直径为 $14mm$ 以上），LH 开始明显上升，较早卵泡期升高近 3 倍。排卵前，雌激素水平快速升高，对促性腺激素分泌起促进性正反馈效应。卵泡分泌稳定的 $E_2$，其血清浓度大于 $200\sim300pg/ml$，持续 $48.7\pm9.3$ 小时诱导出 LH 峰值。在排卵前 1 天 LH 迅速升高达到峰值，LH 峰值是早卵泡期基础 LH 值的十几倍甚至几十倍，平均高于 FSH 峰值 3 倍，最高者可超过 $200IU/L$。
(3) 排卵发生在 LH 峰值后 $36\sim38$ 小时（也有报道认为 LH 波峰出现和排卵的准确间隔时间为波峰启动后 $35\sim44$ 小时）。峰值出现后次日，也就是月经周期的第 15 天，卵泡破裂排出卵母细胞。排卵后，LH 值迅速下降接近早卵泡期水平，维持低水平直至月经周期结束。
(4) 黄体的分泌功能依赖于 LH 的支持，但黄体中期因升高的雌、孕激素又会出现抑制性负反馈，把此阶段的 LH 压至最低水平，LH 脉冲的频率和幅度均明显下降；黄体晚期 LH 每 24 小时短暂脉冲 1 次。黄体晚期，雌、孕激素水平降低，LH 水平又轻微上升。维持黄体不需要 FSH。

### 雌二醇 ($E_2$)

(1) 早卵泡期，雌激素水平处于最低水平，可达 $40\pm20pg/ml$。随着卵泡的募集，尤其是优势卵泡的生长，雌激素水平逐渐升高，在排卵前达到峰值。雌激素的峰值具有短暂的促进性正反馈作用（还有其他各种激素和因子的共同作用），可刺激垂体，触发排卵前 LH 和 FSH 的快速、大量释放。$E_2$ 峰值出现次日，LH、FSH 峰出现，诱发排卵。
(2) 排卵后 $E_2$ 水平迅速下降，但很快黄体形成，黄体开始分泌雌激素、孕激素，雌激素水平又开始逐渐升高，在排卵后 $6\sim9$ 天达到黄体期峰值平台。
(3) 如果受精卵着床，滋养细胞分泌的人绒毛膜促性腺激素 (HCG) 刺激黄体，黄体功能（此时称妊娠黄体）得以继续维持，雌激素水平继续升高。如未受孕，黄体逐渐萎缩，雌激素水平开始逐渐下降，在黄体晚期末降到最低水平，随即月经出现。
(4) 雌激素在月经周期中有两个分泌峰值。第一个峰值出现在卵泡成熟排卵前，一个成熟卵泡的血浆 $E_2$ 水平平均为 $200\sim300pg/ml$，范围可以从 $120\sim550pg/ml$ 不等；第二个峰值出现在黄体中期，$E_2$ 水平平均为 $150\pm70pg/ml$。第一个峰值高于第二个峰值，其高低取决于成熟卵泡内颗粒细胞和随后的黄体细胞的分泌功能，两者相差近一倍。

### 孕激素 (P)

(1) 卵泡期的 P 值处于低水平。
(2) 随着优势卵泡的发育，$E_2$ 水平呈指数型上升，由于排卵前 LH 峰值出现，此时 P 水平也轻微升高，反映了颗粒细胞在获得大量的 LH 受体后卵泡走向成熟时，颗粒细胞开始黄素化的准备过程，此时 P 的轻度上升是卵泡成熟的表现之一。
(3) 有文献报道，P 值开始升高是在排卵前 LH 峰出现前 $12\sim40$ 小时。排卵后持续、迅速升高，排卵后的第 $6\sim7$ 天达到峰值，第 $6\sim9$ 天维持在高水平状态，为胚胎植入提供了最佳的分泌期内膜“窗口”。由于 LH 是由脉冲分泌的，所以孕酮也是由脉冲分泌的，然而每天仅抽 1 次血查孕酮水平很难捕捉到这种脉冲的改变。黄体中期 LH 的分泌约每 6 小时脉冲 1 次，在峰值持续数分钟后下降，而人体的心脏像个巨大的搅拌机，故孕酮的分泌随 LH 脉冲分泌所造成的浓度改变只能在某一瞬间可能被捕捉到，故认为，若在黄体中期查 1 次孕酮水平显示偏低，不足以证明黄体功能不足，学者们推荐至少查两次。
(4) 如无胚胎植入，无 HCG 产生，则黄体晚期由于 LH 脉冲的频率和幅度均低，黄体溶解，所以自第 10 天开始，其分泌的雌、孕激素和抑制素 A 在黄体功能寿命的最后 $4\sim5$ 天呈线性下降，至黄体晚期末和早卵泡期水平达到最低水平。

### 睾酮 (T)

(1) 雄激素的水平在整个月经周期中也呈现规律性的变化，但波动较小。
(2) 在早卵泡期，T 值处于较低水平，随着卵泡生长，T 值也逐渐升高，在排卵期达峰值，排卵后下降，在黄体中期比较平稳，黄体晚期开始下降至早卵泡期低水平，在分泌晚期达到最低值。这样的变化规律可能与雄激素是合成雌激素的底物有关。

### 催乳素 (PRL)

(1) 垂体催乳素细胞阵发性分泌催乳素，每天有 $13\sim14$ 个峰值，峰值最多持续 $67\sim76$ 分钟，平均峰值振幅为 $3\sim4ng/ml$，脉冲间隔时间为 $93\sim95$ 分钟，故每天测定的 PRL 水平很容易捕捉到这种阵发性的波动（PRL 周期的曲线呈波动性，而 FSH 和 LH 的曲线呈光滑性）。PRL 每天早上 8 时开始下降，进入谷值，10 至 11 时降至最低，16 时又开始上升，至第 2 天 8 时又开始下降。
(2) 子宫内膜在分泌期，其间质细胞也分泌少量的催乳素。
(3) 雌激素是催乳素的刺激因子，在月经周期中，PRL 随雌激素的变化趋势而相应变化。早卵泡期，雌激素水平低，催乳素水平也低；随着卵泡发育，雌激素逐渐上升，催乳素也上升；排卵前，雌激素达峰值，催乳素也达峰值；排卵后雌激素下降，催乳素也下降；黄体形成，雌激素又上升，催乳素也上升；但当黄体晚期开始，雌激素下降，催乳素不下降，一直以一定的水平维持至月经来潮才下降。如果妊娠，PRL 持续上升。孕激素也是 PRL 的刺激因子。
(4) 催乳素分泌受影响因素很多，如饮食、睡眠、运动、紧张、应激、低血糖等都有可能导致催乳素水平升高 $1\sim2$ 倍，持续时间少于 1 小时，这些应激状态的影响在静坐 1 小时后恢复正常。
(5) 评估催乳素的基础状态，女性应在月经周期第 $2\sim4$ 天，早上空腹，静坐 1 小时，在 10 至 11 时抽血；或进食碳水化合物后 6 小时，中午空腹抽血，并尽量避免因为应激状态引起催乳素一过性的假性升高。

## 性激素测定的临床意义

### 雌二醇测定的临床意义

(1) **测定雌二醇水平**：可了解此时体内雌二醇状态。如果位于早卵泡期水平或低于早卵泡期水平（孕酮很低），但单用黄体酮撤退试验有撤退性出血，则说明雌激素维持生理剂量水平，能够刺激子宫内膜处于增殖期；黄体酮撤退试验无撤退性出血，则说明雌激素水平不足。（子宫性闭经除外）。
(2) **卵巢功能衰退**：基础 $E_2$ 可能升高（卵泡提早发育，这时要注意计数卵泡数目，当基础窦卵泡数目多时，基础 $E_2$ 也会升高）、FSH 正常，提示卵巢储备功能下降，随着年龄增长及卵巢功能衰退加重，就会出现高 FSH、LH，低 $E_2$ 状态。若病人 40 岁之前月经紊乱，两次 $FSH > 25IU/L$（间隔 4 周抽血），则可诊断为早发性卵巢功能不全。
(3) **卵巢功能衰竭**：停经 1 年，基础 $E_2$ 很低而 FSH、LH 升高，尤其两次 $FSH > 40IU/L$ 时，提示卵巢功能衰竭。40 岁之前绝经（停经 1 年），称为卵巢早衰。
(4) **中枢性闭经**：基础 $E_2$、FSH、LH 均呈低水平，单用黄体酮撤退试验阴性，人工周期试验阳性，为低促性腺激素 (Gn) 性闭经，提示病变在下丘脑或垂体。
(5) **$E_2$ 水平过高的其他原因**：可见于残留卵泡囊肿或颗粒细胞瘤、FSH 瘤、妊娠妇女、药物刺激卵巢治疗中、卵巢过度刺激等。

### 孕酮测定的临床意义

(1) **判断排卵**：$P > 3ng/ml$ 提示本周期有 90% 的可能排卵，另外卵泡黄素化未破裂综合征 (LUFS) 约占 10%。
(2) **诊断黄体功能不全**：黄体中期两次测定 $P < 10ng/ml$ 时，考虑黄体功能不全；反之，黄体功能正常。
(3) **黄体萎缩不全**：出血第 $4\sim5$ 天查 P 仍高于生理水平，提示黄体萎缩不全。注意查血 HCG，除外流产。
(4) **监测妊娠黄体**：妊娠早期测定血清 P 浓度，可以评价妊娠黄体功能。若妊娠黄体功能不足，可适时给予外源性 P 补充治疗，挽救因单纯妊娠黄体功能不足时所造成的流产，改善妊娠预后。妊娠早期 P 水平在 $25\sim30ng/ml$ 范围，提示妊娠黄体功能良好。
(5) **先天性肾上腺皮质增生症 (CAH)**：如 17-羟化酶缺乏、21-羟化酶缺乏、$11\beta$-羟化酶缺乏等，均有高孕酮血症。

### 促卵泡生长素测定的临床意义

(1) **判断卵巢功能**：早卵泡期的 FSH 水平，可以帮助判断卵巢功能。在月经周期第 $2\sim4$ 天检测 FSH，可以了解卵巢的储备功能及基础状态。基础 FSH 值受基础 $E_2$ 水平的影响（$E_2$ 抑制性负反馈）。
(2) **中枢性闭经**：基础 FSH 和 LH、$E_2$ 均呈低水平，单用黄体酮撤退试验阴性，人工周期试验阳性，为低 Gn 性闭经，提示下丘脑或垂体功能减退，而二者的区别需借助 GnRH 激发试验。若 GnRH 激发试验阳性，则为下丘脑性闭经；若为阴性，则为垂体性闭经。
(3) **卵巢功能减退**：捕捉到单次基础 FSH 值超过 $10\sim12IU/L$，提示卵巢功能减退；基础 FSH 值连续两个周期 $>25IU/L$，若年龄 $\le40$ 岁，月经紊乱，提示 POI。
(4) **卵巢功能衰竭**：停经 1 年，FSH、LH 升高，$E_2$ 很低，尤其两次 $FSH > 40IU/L$ 时，提示卵巢功能衰竭。
(5) **其他药物影响**：口服避孕药，药物性垂体抑制如 GnRH 激动剂 (GnRH-a)、拮抗剂 (GnRH-A) 治疗后，FSH、LH 及 $E_2$ 均可能会降低。
(6) **垂体 FSH 瘤**：长时间高雌激素水平时，FSH 值仍然正常或升高，伴有卵巢增大，多个囊肿。

### 黄体生成素测定的临床意义

(1) **预测排卵**：排卵前 LH 明显升高，提示 LH 峰出现。LH 峰发生在 $E_2$ 峰之后或同时，突然迅速升高，可达基础值的 $3\sim10$ 倍，持续 $16\sim24$ 小时后迅速下降。排卵前 LH 峰大约出现在卵泡破裂之前 36 小时，由于 LH 峰上升及下降均极快，有时检测的所谓峰值并非 LH 的最高值。尿 LH 峰一般较血 LH 峰晚 $3\sim6$ 小时。LH 峰值结合盆腔超声预测排卵更准确。
(2) **下丘脑或垂体功能减退**：基础 LH 低下、FSH 和 $E_2$ 均低水平，如神经性厌食导致的下丘脑性闭经。
(3) **PCOS**：PCOS 的诊断标准为以下 3 项中满足两项：稀发排卵或无排卵；高雄激素的临床表现和/或高雄激素血症；卵巢多囊性改变（一侧或双侧卵巢直径为 $2\sim9mm$ 的卵泡 $\ge 12$ 个，和/或卵巢体积 $\ge 10ml$），并排除其他引起高雄激素及排卵障碍的疾病后方可诊断。PCOS 病人（特别是瘦型 PCOS 病人）基础 LH 水平升高（超过基础 FSH 值），而基础 FSH 相对低水平，造成 LH 与 FSH 比值升高，$LH/FSH > 1$，称为高 LH 状态，但不作为诊断 PCOS 诊断的标准。
(4) **帮助确定中枢性或外周性性早熟**：基础 LH 有筛查意义，若 $LH < 0.1IU/L$，提示未有中枢性青春期发动；若 $LH > 3.0\sim5.0IU/L$，可肯定已有中枢性青春期发动。
(5) **垂体 LH 瘤**：闭经，低雌激素和 FSH 水平，高 LH 水平，且不受 GnRh-a 抑制。

### 催乳素测定的临床意义

(1) **脑垂体疾患**：是高催乳素血症最常见的原因，其中垂体催乳素瘤最多见，空蝶鞍综合征、肢端肥大症、垂体 TSH 瘤等都可导致 PRL 水平异常升高。
(2) **PCOS**：$10\%\sim30\%$ PCOS 病人伴有 PRL 升高，PRL 多轻度增高。
(3) **甲状腺功能异常**：部分原发性或继发性甲状腺功能减退者，由于促甲状腺激素升高，导致 PRL 增加。
(4) **药物**：某些药物如多巴胺受体拮抗剂、抗组胺药、多巴胺耗竭剂（如甲基多巴、利血平），激素类药物（如雌激素）、口服避孕药、抗雄激素类药物、促甲状腺激素释放激素等，可引起 PRL 水平升高，但大多数升高的 $PRL < 100ng/ml$。
(5) **肝肾功能异常**：慢性肾功能衰竭时，PRL 在肾脏降解异常；肝硬化、肝性脑病时，假神经递质形成，拮抗 PRL 抑制因子 (PIF) 引起 PRL 升高。
(6) **其他**：某些病人 PRL 水平升高，而没有相关临床症状或者其他症状，需要考虑是否存在大分子 PRL 血症或大大分子 PRL 血症。

### 睾酮测定的临床意义

(1) **PCOS**：T 可能正常，也可能呈轻度至中度升高，但一般 $T < 1.5ng/ml$。ASD 可有升高，部分病人有 $DHEA-S$ 升高。若治疗前雄激素升高，治疗后下降，可作为评价疗效的指标之一。
(2) **产生雄激素的肿瘤**：发病前病人月经及生育能力正常，发病后短期内进行性加重的雄激素过多症状，当 T 水平 $> 1.5ng/ml$，$DHEA-S$ 水平 $> 18.9\mu mol/L (726.92\mu g/dl)$， $ASD > 21nmol/L (600ng/dl)$ 时，需要进一步行影像学检查及其地塞米松抑制试验明确诊断。
(3) **间质-卵泡膜细胞增殖症**：T 升高，但 $DHEA-S$ 正常。
(4) **先天性肾上腺皮质增生 (CAH)**：如 21-羟化酶缺乏、$11\beta$-羟化酶缺乏时，T 和 ASD 升高，同时出现血 17-羟孕酮升高，孕酮升高。
