# 多囊卵巢综合征的性激素变化特点

多囊卵巢综合征（PCOS）是青春期及育龄期女性最常见的一种妇科内分泌疾病。临床表现具有显著异质性，主要表现为闭经或月经稀发、雄激素过多症和卵巢多囊样改变，常伴有不孕、肥胖、胰岛素抵抗和血脂异常等代谢综合征。其最重要的病理生理改变就是生殖内分泌及代谢系统功能紊乱，因而体内多种激素水平也发生了变化，而且有异质性表现。因此，性激素测定及其理解在 PCOS 诊治中有重要意义。

## PCOS 性激素水平的变化特点

### 雄激素

血清总睾酮水平正常或轻度升高，通常不超过正常范围上限的 2 倍；可伴有 ASD 水平升高，脱氢表雄酮（DHEA）、硫酸脱氢表雄酮（DHEA-S）水平正常或轻度升高。

### 促性腺激素

部分 PCOS 妇女可能基础 LH 水平升高，导致基础 LH/FSH 的比值升高；基础 FSH、LH 也可以在正常早卵泡期水平；卵巢功能衰退者，基础 FSH 升高；无排卵病人无月经中期的峰值出现；稀发排卵者有时碰巧抽血可检测到排卵期 FSH 和 LH 的峰值。

### 雌激素

PCOS 病人基础 E2 水平正常或轻度升高，相当于正常女性早、中卵泡期水平；稀发排卵者有时碰巧抽血可检测到排卵前的 E2 峰值。

### 孕激素

PCOS 病人由于卵泡发育和排卵功能障碍，无排卵者孕激素低下；稀发排卵者有时碰巧抽血可检测到排卵后的孕酮水平升高。

### 催乳素

有文献报道，10%~30% 的 PCOS 病人有轻度高催乳素血症，可能是由于血清雌激素长时间无波动的偏高，引起中枢多巴胺（DA）分泌下降，或 PCOS 病人垂体促性腺激素细胞过度分泌 LH 的旁分泌作用，引起相邻近的催乳素细胞分泌 PRL 过多所致的。

### 抗苗勒管激素

PCOS 病人血清 AMH 水平较正常女性高 2~4 倍，且在各年龄段均表现出相似的升高趋势，即使到了育龄晚期也仍能维持在相对较高的水平。目前缺乏我国女性各年龄段 AMH 水平的正常值。

## PCOS 性激素的不同表现

### 月经周期第 2~4 天检测结果

**背景**：PCOM 病人，月经不规律，超声提示 PCOM。

| 结果解读 | E2 (pg/ml) | P (ng/ml) | FSH (IU/L) | LH (IU/L) | PRL (ng/ml) | T (ng/ml)* |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **典型 PCOS 的表现** | 65.4 | 0.36 | 4.41 | 13.79 | 36.54 | 0.76 |
| **正常性激素水平** | 31.57 | 0.21 | 7.51 | 2.68 | 16.25 | 0.21 |
| **卵巢功能衰退** | 61.67 | 0.41 | 11.75 | 16.32 | 14.57 | 0.23 |
| **仅睾酮升高** | 42.54 | 0.11 | 8.13 | 7.32 | 19.76 | 0.78 |

\*注：T 正常值 <0.75 ng/ml

### 停经 3 个月检测结果

**背景**：PCOM 病人，停经 3 个月。

| 结果解读 | E2 (pg/ml) | P (ng/ml) | FSH (IU/L) | LH (IU/L) | PRL (ng/ml) | T (ng/ml)* | HCG |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **早卵泡期，高 LH 状态** | 41.51 | 0.21 | 7.51 | 12.68 | 30.25 | 0.21 | (-) |
| **早卵泡期，正常比例的性激素水平** | 53.20 | 0.87 | 6.49 | 2.97 | 4.26 | 0.45 | (-) |
| **围排卵期** | 271.67 | 0.59 | 4.75 | 14.32 | 37.47 | 0.67 | (-) |
| **已排卵，黄体期** | 93.34 | 14.11 | 5.13 | 7.32 | 19.76 | 0.36 | (-) |

\*注：T 正常值 <0.75 ng/ml
