# 常用雌激素、孕激素类药物及其血中测定值

## 雌激素类药物

### 概述

#### 分类

* **根据药物成分**：雌激素类药物可分为合成雌激素和天然雌激素类药物。
    * **合成雌激素类药物**：常用的有苯甲酸雌二醇（1mg 或 2mg/支）；己烯雌酚（1mg/片，恶心呕吐副作用较重，有致肿瘤性，现已少用）；炔雌醇（0.005mg/片）；尼尔雌醇（2mg/片）。
    * **天然雌激素类药物**：常用的有结合雌激素、戊酸雌二醇、17$\beta$-雌二醇等。
* **根据药物剂型**：雌激素类药物可分为片剂、贴剂、膏剂。

#### 常见不良反应

* **生殖系统**：阴道出血形式改变，异常撤退性出血，突破性出血，点状出血；分泌物增多。
* **乳房**：触痛，增大。
* **胃肠道**：恶心，呕吐；胆汁淤积性黄疸；胆囊疾病发生率增加；胰腺炎。
* **中枢神经系统**：头痛，偏头痛，头晕。

#### 使用禁忌

1.  已知或怀疑妊娠者。
2.  原因不明的阴道流血者。
3.  严重肝肾功能障碍病人。
4.  雌激素依赖性肿瘤病人。
5.  乳腺癌、子宫内膜癌、黑色素瘤病人。
6.  近6个月内患有活动性静脉或动脉血栓栓塞性疾病病人。
7.  卟啉病、耳硬化症者。
8.  系统性红斑狼疮病人。
9.  脑膜瘤病人。

### 常用雌激素类药物及其血中测定值

#### 天然雌激素类药物

* **结合雌激素片（倍美力）**
    * 规格：0.3mg、0.625mg/片。
    * 特性：从孕马尿液中提取的含有雌激素类的混合物，同时也属于水溶性雌激素硫酸钠盐混合物，内含雌酮、马烯雌酮和 $17\alpha$-二氢马烯雌酮，还含有少量的 $17\alpha$-雌二醇、马萘雌酮和 $17\alpha$-二氢马萘雌酮，均为其硫酸酯的钠盐。
    * 测定：无法通过测定血中雌二醇水平来体现其效价。
* **结合雌激素乳膏**
    * 规格：14g/支。
    * 特性：结合雌激素可溶于水，从药物释放后，可以很好地经皮肤、黏膜吸收。
    * 测定：无法通过测定血中雌二醇水平来体现其效价。
* **半水合雌二醇贴片（松奇）**
    * 规格：每个贴片含有 1.5mg 的半水合雌二醇活性成分。每个包装中有4个贴片，可维持1个月的治疗。
    * 特性：经皮吸收可避免雌激素的肝脏首过效应，剂量比一般口服剂量低，减少了肝脏的代谢负担。贴片中的晶体起雌二醇储库的作用，每7天给药1次，雌激素含量很低（1.5mg/贴），每天稳定释放雌二醇 $50\mu g$ 进入体循环，生物利用度达到 23%，安全性高。
    * 测定：可以通过测定血中雌二醇水平来体现。个体差异较大，用药时血中 $E_2$ 水平升高，相当于早卵泡期水平。
* **戊酸雌二醇（补佳乐）**
    * 规格：1mg/片。
    * 特性：其口服制剂来源于豆类和薯类植物，进入人体后在肝脏中代谢，脱掉戊酸基，分解成与人体自身雌激素结构完全相同的 $17\beta$-雌二醇，发挥生物学效应。
    * 测定：每天口服 1mg，多次给药后测定血清雌二醇浓度的平均值为 30~40pg/ml。
* **$17\beta$-雌二醇**
    * 特性：每日口服 $17\beta$-雌二醇之后，1mg $17\beta$-雌二醇平均稳态血药浓度约为 $E_2$ 30pg/ml，2mg $17\beta$-雌二醇平均稳态血药浓度约为 $E_2$ 70pg/ml。$17\beta$-雌二醇经阴道用药后血药浓度是口服的 20~30 倍，1mg 阴道用药最大浓度约为 480pg/ml，但个体差异较大。
* **$17\beta$-雌二醇凝胶（艾斯妥凝胶）**
    * 规格：80g/支。
    * 特性：本品经皮给药吸收约为用药剂量的 10%，一计量尺（2.5g）凝胶，相当于吸收 $150\mu g$ 的雌二醇。药物自给药部位经皮内毛细血管缓慢扩散进入全身血液循环。
    * 测定：一计量尺凝胶用后 $17\beta$-雌二醇的血浆浓度平均约为 $E_2$ 80pg/ml，个体差异较大。绝经妇女每天给药半计量尺（1.25g）凝胶，酌情调整用药。
* **雌三醇（欧维婷软膏）**
    * 特性：阴道内使用雌三醇可以在局部产生最佳的有效性，对阴道黏膜 100% 效价，对子宫内膜作用 10% 的效价，对血中雌二醇水平无影响。
* **普罗雌烯（膏剂、胶囊）**
    * 特性：为雌二醇的衍生物，由雌二醇分子结构上的两个羟基上的氢分别被丙基和甲基取代而得，具有雌激素的特性。其双醚分子结构（雌二醇二醚），经皮肤吸收入血量不到 1%，最终代谢物为雌酮和雌二醇。阴道给药使阴道维持较高的药物浓度，不能被阴道上皮吸收，不进入全身血液循环。
    * 测定：无法通过测定血中雌二醇水平来体现。

#### 合成雌激素类药物

合成雌激素包括非甾体类合成雌激素（己烯雌酚）、甾体类合成雌激素（炔雌醇、尼尔雌醇）。主要用于雌激素缺乏或水平低下的相关疾病的治疗，调节性治疗以及与不同的孕激素配伍形成口服避孕药。人工合成雌激素的特点在于药效高，雌激素活性强，但是副反应也较明显。随着结合雌激素等天然雌激素制剂的不断进步和完善，合成雌激素多用于避孕药中，单片制剂在临床上应用越来越少，均无法通过测定血中雌二醇水平来体现。

### 雌激素在临床中的应用

1.  可用于低雌激素闭经病人的激素补充治疗、绝经后激素治疗。
2.  由于天然雌激素制剂对胚胎发育无影响，还可以用于辅助生育技术，促进子宫内膜增殖，为胚胎种植准备。
3.  宫腔粘连手术后应用大剂量雌激素治疗可促进子宫内膜增殖修复，防止再粘连。
4.  异常子宫出血（AUB）病人严重贫血时，可应用雌激素治疗（子宫内膜修复法）止血。
5.  绝经后取出宫内绝育器前应用雌激素，可减少手术难度；结合雌激素乳膏制剂、雌三醇软膏或雌醚可治疗外阴和阴道萎缩（局部用药）。

## 孕激素类药物

孕激素属于甾体激素，既可作为单一制剂存在，也常与雌激素等药物组合成复合制剂应用于临床。临床中孕激素类药物可用于辅助生育和黄体支持，控制月经周期，激素替代治疗、人工周期，治疗子宫内膜恶性肿瘤及癌前病变，药物避孕等。

### 概述

#### 分类

* **根据药物成分**：孕激素类药物可分为天然孕激素和人工合成孕激素类药物。
    * **天然孕激素类药物**：主要有黄体酮针剂和口服制剂。
    * **人工合成孕激素**：
        * 孕酮衍生物：包括甲羟孕酮（安宫黄体酮）、甲地孕酮、环丙孕酮。
        * 睾酮衍生物：包括左炔诺孕酮、炔诺酮、去氧孕烯、孕二烯酮、诺孕酯、地诺孕素，是口服避孕药常用的类型。
        * 19-去甲孕酮类：包括地美孕酮、普美孕酮、曲美孕酮、诺美孕酮、醋酸烯诺孕酮、己酸孕诺酮。
        * 螺旋内酯衍生物：屈螺酮，能有效拮抗雌激素制剂的水钠潴留副作用。
* **根据药物剂型**：孕激素类药物可分为针剂、片剂、丸剂、胶囊剂（可口服也可以置阴道内）、霜剂（阴道内用）、缓释剂（可置子宫腔内、阴道内或皮下埋置）。

#### 常见不良反应

* **生殖系统**：轻微阴道出血，经期血量改变、闭经、乳房疼痛，性欲改变。极少数病人可出现突破出血，一般增加剂量即可防止。
* **胃肠道**：呕吐、腹痛。
* **肝脏**：肝功能改变、黄疸。
* **中枢神经系统**：头疼、偏头痛、抑郁、精神紧张等。
* **皮肤**：皮肤过敏、荨麻疹、瘙痒、水肿。

#### 使用禁忌证

1.  对药物制剂成分过敏者。
2.  不明原因阴道出血者。
3.  严重肝功能障碍者。
4.  妊娠期或应用性激素时发生或加重疾病者，如严重瘙痒、阻塞性黄疸、妊娠期疱疹、卟啉病和耳硬化症者。
5.  孕激素相关的脑膜瘤病人。
6.  有血栓性疾病史者。

### 常用孕激素类药物及其血中测定值

#### 天然孕激素类药物

* **黄体酮针剂（油性针剂）**
    * 规格：10mg/支，20mg/支（1ml: 10mg; 1ml: 20mg）。
    * 药代动力学：由注射液肌内注射后迅速吸收，6~8小时血药浓度达高峰，之后逐渐下降，可持续48小时，在肝内代谢，约12%代谢为孕烷二酮，代谢物与葡萄糖醛酸结合随尿排出。
    * 测定：每天 20mg 黄体酮肌内注射后，48小时达到稳态，在下一次用药前测定血中孕酮水平升高约 $7ng/ml$，个体差异较大。
* **微粉粒化黄体酮**
    * 特性：黄体酮胶囊或胶丸，口服或阴道用药。生产厂家不同，药代动力学有差异。口服后在肝内代谢，约 12% 代谢为孕烷二醇，代谢物与葡萄糖醛酸结合随尿排出。
    * 药代动力学参数：例如黄体酮胶囊安琪坦和益玛欣，200mg，每日2次（bid）的阴道或口服给药药代动力学参数（病人数 = 16）如下表。

| 参数 | 单位 | 益玛欣（阴道） | 安琪坦（阴道） | 益玛欣（口服） | 安琪坦（口服） |
| :--- | :--- | :--- | :--- | :--- | :--- |
| $C_{max(last)}$ | $ng/ml$ | $9.13 \pm 8.09$ | $12.30 \pm 1.60$ | $62.97 \pm 40.59$ | $169.53 \pm 130.24$ |
| $T_{max(last)}$ | $h$ | $9.72 \pm 10.50$ | $11.03 \pm 9.62$ | $2.88 \pm 1.35$ | $2.06 \pm 1.55$ |
| $t_{1/2}$ | $h$ | $20.21 \pm 18.97$ | $20.66 \pm 10.22$ | $26.12 \pm 4.78$ | $22.78 \pm 6.30$ |
| $AUC_{\tau(ss)}$ | $h \cdot ng/ml$ | $261.42 \pm 74.36$ | $116.83 \pm 19.72$ | $274.86 \pm 160.28$ | $472.00 \pm 250.54$ |
| T达稳态 | $h$ | $58.50 \pm 24.74$ | $39.00 \pm 12.00$ | $55.50 \pm 33.62$ | $58.50 \pm 31.56$ |
| $C_{o()}$平均 | $ng/ml$ | $20.43 \pm 6.16$ | $9.82 \pm 1.36$ | $11.69 \pm 4.97$ | $15.41 \pm 6.65$ |

* **数据解读**：由上表可见，益玛欣 200mg, bid, 阴道给药，稳定状态后血中孕酮水平为 $(20.43\pm6.16)ng/ml$；安琪坦 200mg, bid, 阴道给药，稳定状态后血中孕酮水平为 $(9.82\pm1.36)ng/ml$。益玛欣 200mg, bid, 口服给药，稳定状态后血中孕酮水平为 $(11.69\pm4.97)ng/ml$；安琪坦 200mg, bid, 口服给药，稳定状态后血中孕酮水平为 $(15.41\pm6.65)ng/ml$。
* **黄体阴道缓释凝胶**
    * 特性：含有 90mg(8%) 黄体阴道缓释凝胶阴道给药后，血清孕酮浓度增加缓慢，约8小时达到峰值，每天使用，研究显示在第1天和第5天有明显的累积效应，第6天以后测定血清孕酮水平位于 10ng/ml 左右，个体差异较大。

#### 地屈孕酮（达芙通）

* 规格：10mg/片。
* 特性：地屈孕酮是一种逆转孕酮（孕酮的立体异构体之一），是经过紫外线照射后在 C6 和 C7 之间有个额外的双键，碳 9、10 位的甲基和氢原子逆转所形成的旋光异构体，是最接近天然的孕激素。所有代谢产物的结构均保持 4,6-二烯-3-酮的构型。
* 测定：口服标记过的地屈孕酮，平均 63% 随尿排出，72 小时体内完全清除。地屈孕酮在体内完全被代谢，主要的代谢物是 10, 11-二羟基衍生物（DHD）。由于 DHD 大多以葡萄糖醛酸化合物在尿中测定，所以检测地屈孕酮的浓度需要特殊的实验室条件，无法通过测定血中孕酮水平来体现。

#### 合成孕激素类药物

1.  **甲羟孕酮（安宫黄体酮）**：2mg/片，大剂量的有 200mg/片、250mg/片、500mg/片。口服后在胃肠道吸收，在肝内降解。肌内注射后 2~3 天血药浓度达到峰值。肌内注射长效甲羟孕酮 150mg 后 6~9 个月才会检测不到药物，血中醋酸甲羟孕酮水平超过 0.1mg/ml 时，LH 和 $E_2$ 均会受到抑制而抑制排卵。
2.  **甲地孕酮**：1mg/片，大剂量的有 40mg/片、160mg/片。口服后生物半衰期明显比左炔诺孕酮短，大部分代谢产物以葡萄糖醛酸酯形式排出。
3.  **炔诺酮（妇康片）**：0.625mg/片。口服后从胃肠道吸收，血药峰值时间为 0.5~4 小时，平均 1.17 小时，半衰期为 5~14 小时，血浆蛋白结合率为 80%，作用持续至少 24 小时，吸收后大多与葡糖醛酸结合，由尿排出。
4.  **孕三烯酮（内美通）**：2.5mg/胶囊。口服后 2.8~3.1 小时达血药峰浓度。血浆半衰期大约为 24 小时。口服 3 天后血浆浓度是最大血浆浓度的 5%，在第 2 次服用后达到稳态血药浓度。

**注**：以上合成孕激素类药物均无法通过测定血中孕酮水平来体现。

### 孕激素在临床中的应用

1.  **闭经方面的应用**
    对于已除外妊娠的闭经病人，孕激素试验用于评估雌激素水平并确定闭经程度。由于药代动力学的原因，黄体酮针剂 20mg/天，肌内注射 3 天，观察有无撤退性出血为最敏感试验。
2.  **无排卵性异常子宫出血方面的应用**
    主要包括孕激素撤退法（也称子宫内膜脱落法）和孕激素内膜萎缩法，以及为控制月经周期，在月经后半期定期用孕激素 12~14 天。
3.  **先兆流产**
    黄体功能异常是导致早期妊娠流产的重要原因之一。妊娠黄体功能不足可导致孕激素水平低下，进而发生妊娠蜕膜反应不良，影响胚胎发育；而且低水平孕酮会导致子宫平滑肌易激惹，引发流产。临床生理情况下，孕早期孕酮生理水平为 $(25\pm5) ng/ml$。目前针对先兆流产的治疗手段十分有限，补充孕激素仅能挽救单纯因孕激素不足所造成的流产。
4.  **体外受精-胚胎移植（IVF-ET）**
    试管婴儿技术中造成黄体功能不全，取卵后需要通过较大剂量的孕激素进行黄体支持。
5.  **黄体功能不全**
    补充合适剂量的孕激素，或用 HCG 刺激自身黄体的建立。
