# 性激素测定的方法及优缺点
## 性激素测定的常用方法

### 放射免疫分析法 (RIA)

1. 该技术是将抗原、抗体反应的高度特异性与放射性同位素检测技术的高度灵敏性相结合而建立的检测技术，提高了灵敏度，使免疫分析从定性变为定量，从常量分析提高到微量。
2. 样本用量少，操作简单，试剂成本低是 RIA 的优点。
3. 缺点是该方法受同位素半衰期的影响较大，标记抗原或抗体的不断衰变使每次实验必须同时做标准曲线，不便于短期内发出报告。另外，由于放射性同位素不可避免的污染环境，使其逐渐被淘汰。

### 酶联免疫吸附分析 (ELISA)

1. 酶取代放射性核素作为示踪剂，催化底物起放大信息的作用，通过检测显色底物在酶催化下产生的吸光度值测定性激素水平。
2. 与放射免疫分析法比较，其优点在于可利用存储的标准曲线。
3. 缺点是起反应的底物有毒，酶不稳定，反应需要严格控制温度和 pH 值。此外，该方法灵敏度和重复性低于放射性免疫分析。

### 化学发光免疫分析 (CLIA)

1. 该方法将发光物质或酶标记在抗原或抗体上，经过免疫反应后，加入氧化剂或酶底物发光，通过检测发光强度实现样品的定量。
2. 既具有免疫反应的特异性，又有发光反应的高灵敏度，同时具备线性范围宽、标记物有效期长、操作简便、易于实现全自动化、减少人为操作误差等优势。
3. 缺点是试剂成本较高，仪器费用昂贵。

### 电化学发光免疫分析 (ECLIA)

1. 该方法是继放射免疫分析、酶免疫分析、化学发光免疫分析测定以后的新一代标记免疫测定技术。它将电化学发光和免疫测定相结合，在电极上施加一定的电压或电流时，电极上发生电化学反应，在电极反应产物间，或电极反应产物与溶液中某种组分之间发生化学反应而产生激发态，当激发态返回基态时产生化学发光现象。
2. 具有标记物稳定、灵敏度高、重现性好、光信号线性宽等优点，目前最为广泛应用。

### 液相色谱-质谱联用 (LC-MS)

1. LC-MS 将高分离能力的色谱技术与高灵敏、高专属性的质谱技术联系起来，成为一种多用途、高灵敏的定性、定量分析方法。
2. 具有高灵敏度、高选择性、高效率、高可靠性等优点，常被作为激素测定的鉴定方法。如用 ECLIA 测定出高孕酮水平或高睾酮水平时，若与临床表现不符合，则可再用 LC-MS 重新测定，极有可能是正常范围。
3. 由于该方法对分析技术和仪器要求高，且仪器价格昂贵，操作复杂，所以目前尚未广泛应用于临床。

## 不同性激素测定系统的性能比较和结果可比性

虽然液相色谱-质谱联用是目前可靠性最好的方法，但由于其仪器昂贵、操作复杂等原因，尚未广泛应用。而放射性免疫和酶联免疫由于各自的局限性已经逐渐被淘汰，目前实验室多采用化学发光或电化学发光免疫分析测定性激素。

虽然不同化学发光分析系统的反应原理基本类似，但由于试剂成分的差异，尤其是抗体的来源不同等原因，性激素检测尚无统一的溯源，未实现检测标准化。

如同一性激素项目在使用不同测定方法的实验室之间得出的检测结果不尽相同，有一定的偏差；即使是相同的测定方法，由于生产仪器的厂家不同，测定出的结果也存在偏差；同一个厂家生产的相同测定方法的仪器，由于仪器型号的不同，测定的结果存在偏差；同一个型号仪器进行操作的技术员不同（技术员进行定标和质量控制），测定的结果存在偏差；同一份血样在同一个型号仪器进行稀释后测定，存在测定的允许范围内的偏差；同一份血样在同一个型号仪器进行复测时，存在测定偏差。

以上可能出现的情况提示临床医生应该了解性激素检测的基本性能及结果之间的差异；在应用性激素检测结果结合临床时，应综合分析；若是检测治疗结果，则应尽可能选择同一个平台的检测系统。

## 性激素测定的影响因素

1. **受试者准备**：因恐惧、紧张、激动等状态均可导致病人 PRL 分泌量变化，使血中 PRL 水平相对升高。受试者应在平静、休息状态时采取坐位抽血。
2. **样本采集时间**：性激素水平随女性月经周期呈规律性波动，故应根据诊疗需求确定不同的采样时间。
3. **样本的处理**：样本采集后，尽快离心分离血清并检测。样本在采集、运送、保存时应注意做好标识并避免污染。
4. **每次检测的性激素结果会有变化**：每个月经周期的基础雌激素水平受本周期卵泡数量、大小、颗粒细胞的数量和分泌性激素功能强弱的影响，负反馈对 FSH 和 LH 的抑制的不同，造成每个月经周期的基础性激素水平不同。
5. **服用恒定量的外源性性激素，每次的检测结果不同**：如果测定的是外源性雌激素或孕酮在体内的水平，由于其受个体对雌激素或孕酮代谢不同的影响，所以即使同一个个体每天服用相同剂量的雌二醇或肌内注射相同剂量的黄体酮，而每天受外界及进食、代谢的影响，造成测定的水平有所波动。
6. **总睾酮的测定**：目前全球没有统一的总睾酮检测方法与正常范围，通常以每个测定单位制定的正常范围为准，这样有可能导致同一份血样在这个平台上测定为不正常，而在另一个平台测定为正常范围，存在一定偏差。
