# 性激素检测化验单解读

性激素六项（有时加上 HCG）常常同时检测，因为它们之间有相互促进或制约的关系，故不可窥见一斑。分析性激素化验单时，一定要注意抽血时的状态是月经第 $2\sim4$ 天或月经失调时，还是无法计算月经周期第几天。

## 月经周期第 $2\sim4$ 天性激素检测化验单解读

### 化验单 1

| FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$)|
| :--- | :--- | :--- | :--- | :--- | :--- |
| 6.51 | 4.63 | 32.12 | 0.32 | 11.16 | 0.24 |

**解读**：上述结果提示本周期的基础性激素化验单均在正常范围。

###化验单 2

| FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$)|
| :--- | :--- | :--- | :--- | :--- | :--- |
| 16.57 | 4.67 | 56.45 | 0.48 | 17.23 | 0.33 |

**解读**：$FSH \ge 10IU/L$，余正常，提示卵巢功能已经衰退。

### 化验单 3

| FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$)|
| :--- | :--- | :--- | :--- | :--- | :--- |
| 8.42 | 5.72 | 12.54 | 0.31 | 13.57 | 0.16 |

**解读**：$E_2$ 水平低于正常范围，余正常。临床上经常误诊为低雌激素血症。但需要注意的是，病人为月经期第 $2\sim4$ 天抽血检测，无论是自然月经来潮，还是单用黄体酮撤退出血，均不能诊断为低雌激素血症，该性激素化验单指标均属正常范围。

### 化验单 4

| FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$)|
| :--- | :--- | :--- | :--- | :--- | :--- |
| 4.41 | 13.79 | 65.54 | 0.43 | 36.54 | 0.76 |

**解读**：$LH > FSH$，$E_2$ 略升高，轻度的 PRL 升高，轻度的总睾酮升高，为典型的 PCOS 病人的性激素化验单。

### 化验单 5

| FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$)|
| :--- | :--- | :--- | :--- | :--- | :--- |
| 4.32 | 3.28 | 90.42 | 0.18 | 25.64 | 0.62 |

**解读**：$E_2$ 升高，FSH、LH 偏低，余正常。用超声帮助判断，可能有残留卵泡囊肿，也可能有几个较大的卵泡，两者均为卵巢功能不好。注意不能单看基础 FSH 不高，就认为是卵巢功能好。

### 化验单 6

| FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$)|
| :--- | :--- | :--- | :--- | :--- | :--- |
| 6.57 | 4.62 | 72.38 | 0.41 | 18.45 | 0.48 |

**解读**：$E_2$ 偏高，余正常。用超声帮助诊断，可能有卵巢多囊样改变 (PCOM)，或有一个较大卵泡（卵泡提早发育）。如果没有超声帮助，依据病人年龄来初步判断，如果病人 < 30 岁，则为正常（因为育龄女性，$70\%\sim80\%$ 为 PCOM 表现），如果病人 > 35 岁，则与年龄相符，为卵泡提早发育，卵巢功能已开始衰退。

### 化验单 7

| FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$)|
| :--- | :--- | :--- | :--- | :--- | :--- |
| 28.43 | 5.72 | 113.54 | 0.48 | 25.67 | 0.59 |

**解读**：$E_2$ 水平升高，FSH 水平升高，而 LH 不高，余正常，提示残留卵泡囊肿。

### 化验单 8

| FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$)|
| :--- | :--- | :--- | :--- | :--- | :--- |
| 28.43 | 55.72 | 113.54 | 0.48 | 25.67 | 0.59 |

**解读**：在化验单 7 结果的基础上只改动 LH 值，LH 和 FSH 都升高，$LH > FSH$，$E_2$ 水平升高，提示病人不是在真正的月经第 2 天检测的，而是把围排卵期出血当成月经第 2 天了。

### 化验单 9

**病史**：病人平素月经规律。

| FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$)|
| :--- | :--- | :--- | :--- | :--- | :--- |
| 7.77 | 5.32 | 67.62 | 2.41 | 14.57 | 0.43 |

**解读**：孕酮轻度升高，时常被误认为是高孕酮血症，雌激素轻度升高，余正常。真正的高孕酮血症（肾上腺皮质功能亢进）病人的月经是不规律的，因此这种情况多考虑黄体没有溶解完全，建议病人在月经量鲜血增多时的第 2 天进行抽血检测。

### 化验单 10

**病史**：病人平素月经规律。

| FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$)|
| :--- | :--- | :--- | :--- | :--- | :--- |
| 3.13 | 0.32 | 142.63 | 7.89 | 46.76 | 0.36 |

**解读**：雌激素、孕酮均升高，FSH 和 LH 值偏低，PRL 升高。注意此时补查血 HCG，若 HCG 升高（如 $79mIU/ml$），则提示妊娠的先兆流产，不是来月经。

## 停经或无法计算月经周期性激素检测化验单解读

若停经或无法计算在月经周期的哪个时间段进行性激素检测，则可以马上抽血，查性激素六项，有性生活史者可加查 HCG。

### 化验单 1

**病史**：病人，女，32 岁，停经 5 个月。

| HCG ($mIU/ml$) | FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$) |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 0.01 | 2.58 | 1.21 | 18.41 | 0.34 | 86.21 | 0.19 |

**解读**：HCG 阴性，排除妊娠；孕酮低，说明未排卵；$E_2$、FSH、LH 均低，但 PRL 升高，睾酮值正常，说明升高的 PRL 抑制了下丘脑和垂体；Gn 低，导致卵泡不发育；$E_2$ 低，故而停经，符合高催乳素血症抑制了生殖内分泌轴的表现。

### 化验单 2

**病史**：病人，女，26 岁，闭经 2 年。

| HCG ($mIU/ml$) | FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$) |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 0.01 | 3.25 | 0.12 | 10.31 | 0.11 | 6.71 | 0.13 |

**解读**：所有的值均偏低，虽然考虑中枢性闭经，但需要通过黄体酮撤退试验来检验子宫内膜有无受到雌激素作用。如果黄体酮撤退试验阴性，则认为低水平的雌激素没有刺激子宫内膜发生增殖性改变，还需要进一步试验，给予人工周期用药。除外子宫性闭经，如果黄体酮撤退试验阴性，人工周期试验阳性，则证实是下丘脑-垂体性闭经。如何分析是下丘脑性闭经，还是垂体性闭经，需要进行 GnRH 激发试验。

### 化验单 3

**病史**：病人，女，28 岁，闭经 8 个月。

| HCG ($mIU/ml$) | FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$) |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| (-) | 55.12 | 37.57 | 13.42 | 0.14 | 18.71 | 0.16 |

**解读**：FSH 值高，$E_2$ 水平低，提示卵巢功能严重衰退。如果 4 周后复查示：FSH $45.62IU/L$，LH $32.41IU/L$，$E_2$ $21pg/ml$，则可诊断为早发性卵巢功能不全 (POI)。

### 化验单 4

**病史**：病人，女，32 岁，闭经 1 年余。

| HCG ($mIU/ml$) | FSH ($IU/L$) | LH ($IU/L$) | $E_2$ ($pg/ml$) | P ($ng/ml$) | PRL ($ng/ml$) | T ($ng/ml$) |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| (-) | 68 | 54 | 18.1 | 0.02 | 15.61 | 0.04 |

**解读**：FSH 值高，$E_2$ 水平低，如果单用黄体酮撤退性出血阴性，结合病人 32 岁、已闭经 1 年余的情况，则可诊断为卵巢早衰。
