# 性激素测定在生殖医学领域的应用

在生殖医学领域，**性激素测定**主要用于以下方面：
* 评估**卵巢功能**。
* 决定**药物刺激卵巢方案和药物调整**并**监测其效果**。
* 预测可能的**获卵数**。
* 评估**黄体支持的疗效**。

## 对卵巢储备功能的评价

### 基础 FSH、E₂

* 当卵巢功能减退时，**垂体分泌 FSH 增加**。
* **基础 FSH 值**是判断卵巢储备功能和预测卵巢对药物反应的**主要指标**。
* 在月经周期第 2 天测定 FSH，如果浓度**高于 $12 IU/L$**，则提示动员这批卵泡生长困难，本周期**不强行进入刺激卵巢治疗**。
* 部分卵巢功能减退病人，卵泡期缩短，过早的卵泡发育，导致**基础 E₂ 水平升高**。
* 需结合**超声**了解**窦卵泡数（AFC）**和大小。如果卵泡大小明显不均匀，则本周期**不强行进入刺激卵巢治疗**。

### 抗苗勒管激素（AMH）

* AMH 水平被认为是评价**体外受精-胚胎移植 (IVF-ET)** 中预测**卵巢过度刺激综合征 (OHSS)** 风险的**最好的指标**。
* **AMH 和 AFC** 是评价卵巢功能及**控制性卵巢刺激 (COS)** 效果的**最好指标**。
* **AMH 过高**，COS 过程中卵巢高反应发生率增加。

---

## 对 COS 过程的监测及用药的调整

### 评估 GnRH-a 的抑制作用

* 给予 **GnRH-a** 使垂体脱敏，卵巢处于相对静止状态。
* 在应用早期，可导致垂体大量释放 LH 和 FSH，血中 FSH 浓度可增加 5 倍，LH 可增加 10 倍。
* 之后由于形成大量的 GnRH-a/受体复合物，导致受体数量减少，使垂体合成和释放 FSH 和 LH 功能降低。
* 在 **GnRH-a 长方案**中，于前一周期的黄体中期应用 GnRH-a，应用 14 天左右，此时垂体处于脱敏状态。
* 检测血中 **FSH、LH、E₂ 的水平**，可评估垂体和卵巢的抑制状态，即血 $LH < 5 IU/L$，$E_{2} < 50 pg/ml$；超声测 AFC 大小均匀，符合降调节满意的标准。

### 监测卵泡的发育情况

* 根据**超声**监测卵泡生长情况。
* 通过检测**血 E₂ 水平、LH 水平、孕酮水平**来微调促性腺激素药物剂量和类型。
* 监测 **LH 峰**是否过早出现，如果提前出现 LH 峰，可给予拮抗剂 **GnRH-A** 抑制 LH 峰。

### 预防卵巢过度刺激综合征（OHSS）

* 在 COS 过程中，对卵巢反应的监测主要依靠**超声**和测定**血中 $E_{2}$ 的浓度**。
* **过高的 $E_{2}$ 浓度**提示 OHSS 风险增高，需及时调整 Gn 用药，避免发生 OHSS。
* $E_{2} < 1000 pg/ml$ 时，无 OHSS 风险。
* $E_{2} > 4000 pg/ml$ 时，OHSS 风险明显增加。

### 与超声协同诊断卵泡黄素化未破裂综合征（LUFS）

* **LUFS** 是指有优势卵泡发育，但 **LH 峰后 48 小时卵泡不破裂**，颗粒细胞已发生黄素化的一种临床症候群。
* 表现为**超声特征图像**及**血 P 值升高**。

---

## 预测卵子质量、胚胎质量和妊娠结局（相关性不强）

### 预测卵子质量、胚胎质量

* **AMH** 与**获卵数目相关性明确**，但是与卵子质量、胚胎质量的相关性还在争论中。
* 如 **AMH 水平**较基础 FSH 更能预测**获卵数目及卵子质量**。
* AMH 水平能够预测**胚胎形态学**和**囊胚形成率**。
* 卵泡液中的 **AMH** 可预测 IVF-ET 后**胚胎发育和种植潜能**。

### HCG 对妊娠结局的预测作用

* 检测**怀孕日 HCG 的水平**与妊娠结局成**正相关**。
* HCG 值愈高，良好妊娠结局可能性愈高。

---

## 评估黄体支持治疗效果

* 自然周期中血 **P（孕酮）浓度**：
    * 排卵前为 $< 1.5 ng/ml$。
    * 排卵后 $> 3 ng/ml$。
    * 早孕期以超过 $25 ng/ml$ 为宜。
* 在 **IVF-ET 过程中**，由于垂体被抑制，LH 不足，**常规需要进行黄体支持**。
* 测定**血中孕酮水平**可指导及时补充药物及停用药物。
