# 更年期女性的性激素变化特点

更年期是传统名称，指绝经及其前后的一段时间，是从生殖期过渡到老年期的一个特殊生理阶段，包括围绝经期前后。在这个过程中女性激素会发生明显的变化。

## 绝经、绝经过渡期、围绝经期、绝经后期的概念

### 绝经

绝经是一个回顾性诊断，当妇女一生中的最后 1 次月经已过去 1 年便可以诊断绝经，而绝经的年龄是最后 1 次月经的时间，意味着卵巢功能的衰竭。绝经年龄平均为 50 岁。

### 绝经过渡期

绝经过渡期是指 40 岁以后的妇女，从规律的月经周期开始变得不规律，伴有或不伴有潮热症状，直至最后 1 次月经的时期。

### 围绝经期

围绝经期的起点同绝经过渡期，终点为最后 1 次月经后 1 年，之后进入绝经后期。多数女性的围绝经期始于 40 岁以后，平均年龄为 45 岁，持续 1~10 年，平均 4~5 年。

### 绝经后期

绝经后期是指从绝经一直到生命终止的这段时期。

## 绝经过渡期和绝经后临床常用性激素检测的意义

在应该绝经的年龄段停经 1 年以上，就可以诊断绝经，不需要常规查性激素。如果围绝经期病人仍有生育的要求，可以在月经 2~4 天进行性激素检测。检测的目的是评价病人卵巢储备功能，给病人一些临床建议，充分告知其生育的概率。当 40 岁以上女性出现月经紊乱或者出现停经时，进行性激素检测，可帮助诊断。

### 雌激素

-   由于卵泡数目的减少直至耗竭，卵巢功能逐渐衰退，雌激素水平从不稳定的波动状态渐渐下降，在绝经后的数年内达到稳定的低水平。
-   女性体内的雌激素在绝经前以雌二醇（$E_2$）为主，绝经后变成以雌酮（$E_1$）为主。绝经后血 $E_2 < 10 \sim 20\text{pg/ml}$。
-   **最佳检测时间**：仍有月经来潮的女性，在月经 2~4 天检测，了解基础状况。
    -   基础 $E_2$ 正常值为 $(40 \pm 20)\text{pg/ml}$。
    -   如果 $E_2 > 80\text{pg/ml}$，可能卵泡提早发育，考虑卵巢储备功能低下。
    -   如果已停经，为了诊断，可以随时抽血，再加以判断。

### 孕激素

-   绝经过渡期的妇女经常有卵泡生长，但无排卵，孕酮水平低下，月经紊乱。绝经后无孕酮分泌。
-   **最佳检测时间**：
    -   仍有月经来潮的围绝经期女性，经前 1 周检测；或行 BBT 测定（最为经济）。
    -   临床中经常有月经少者，如果 BBT 双相，提示有排卵，也无生育要求，无需处理。

### 雄激素

-   绝经后雄激素来源于卵巢间质细胞及肾上腺，总体雄激素水平下降。
-   绝经后雄激素/雌激素比值升高，其与雌激素明显减少相关。绝经后女性可呈现轻度多毛症，与上述性激素比值变化相关。
-   **检测时间**：
    -   可选择任何时间检测总睾酮，而 ASD、DHEA-S 并不作为常规检验项目。
    -   如果病人月经不规律或者绝经后出血，同时合并有卵巢肿瘤，要考虑可能有分泌激素功能卵巢肿瘤的可能性。

### 促性腺激素

-   从绝经过渡期开始 FSH 可能上升或正常，受到 $E_2$ 负反馈的影响，在绝经 1~3 年后上升并达高峰。
-   月经早期血清 FSH > 10~12 IU/L，提示卵巢储备功能下降。
-   绝经过渡期 FSH 水平升高，呈波动型，LH 仍可在正常范围。
-   绝经后垂体释放 FSH 和 LH 增加，FSH 升高较 LH 更显著。
-   **最佳检测时间**：仍有月经来潮的女性，在月经周期的第 2~4 天检测；如已停经，则可在任何时间检测。

### 催乳素

-   绝经后由于雌激素水平下降，下丘脑分泌催乳素抑制因子（PIF）增加，使催乳素浓度降低。

## 围绝经期性激素变化

### 月经第 2~4 天检测

| E2 (pg/ml) | P (ng/ml) | FSH (IU/L) | LH (IU/L) | PRL (ng/ml) | T (ng/ml) | 结果解读 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 32.67 | 0.43 | 26.94 | 4.68 | 16.81 | 0.32 | 卵巢功能衰退 |
| 22.14 | 0.36 | 9.41 | 6.48 | 23.62 | 0.56 | 本周期性激素正常 |
| 110.61 | 0.11 | 6.48 | 3.26 | 15.47 | 0.12 | 残留卵泡囊肿 |
| 80.64 | 0.57 | 18.64 | 7.48 | 18.41 | 0.47 | 卵泡提早发育，卵巢功能衰退 |

### 停经数月者随时检测

| E2 (pg/ml) | P (ng/ml) | FSH (IU/L) | LH (IU/L) | PRL (ng/ml) | T (ng/ml) | HCG | 结果解读 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 15.61 | 0.11 | 48.47 | 32.61 | 11.54 | 0.11 | (-) | 卵巢功能严重衰退 |
| 48.11 | 0.32 | 15.67 | 3.48 | 18.69 | 0.32 | (-) | 尚有生理剂量的雌激素水平，用黄体酮撤退可以有撤退性出血 |
| 140 | 0.36 | 68.47 | 88.64 | 25.64 | 0.48 | (-) | 目前是围排卵期 |
| 86.4 | 8.42 | 7.64 | 8.48 | 21.11 | 0.36 | (-) | 黄体期，观察 |
| 90.40 | 10.12 | 3.10 | 0.48 | 46.56 | 0.41 | 116.54 | 妊娠，但妊娠黄体功能不足 |
